version: '3.8'

services:
  app:
    build:
      context: ./fastapi
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app
    container_name: fastapi_compose
